### ISSUE TITLE
Research branch update

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/research#15] opened 2024-03-01 15:50 UTC
**Update documentation**: https://github.com/web3privacy/docs/blob/main/docs/research/index.md

1. Write down how our Research works.
2. Collect all finished, actual & planned research.
3. Write down how to contribute.
4. Collect & publish useful links.

**Sync with the website**: https://web3privacy.info/research/

- Update research page description
- Update reports' list
- Add description to every report
- Provide useful links for contributors: docs, contribution guide etc

**Comment by Msiusko** [comment] 2024-03-01 16:07
Updated general docs index.md: https://github.com/web3privacy/docs/blob/main/docs/research/index.md

_Added missing research_
- https://github.com/web3privacy/docs/blob/main/docs/research/Privacy-use-cases-UA-RU-war.md
- https://github.com/web3privacy/docs/blob/main/docs/research/Scoring-model.md
- https://github.com/web3privacy/docs/blob/main/docs/research/diversity-privacy.md
- https://github.com/web3privacy/docs/blob/main/docs/research/grants.md
- https://github.com/web3privacy/docs/blob/main/docs/research/privacy-services-db.md

**Comment by burningtree** [comment] 2024-03-02 02:09
Cool!

Just please keep the rule that in the Research project/repository 1 issue = 1 research. If the issue is not research, but a specific task, it should be somewhere else (for example Core Project or you can create another).

This issue is basically duplicate of web3privacy/core#37

**Comment by burningtree** [comment] 2024-03-02 06:10
> Updated general docs index.md: https://github.com/web3privacy/docs/blob/main/docs/research/index.md
> 
> _Added missing research_
> 
> * https://github.com/web3privacy/docs/blob/main/docs/research/Privacy-use-cases-UA-RU-war.md
> * https://github.com/web3privacy/docs/blob/main/docs/research/Scoring-model.md
> * https://github.com/web3privacy/docs/blob/main/docs/research/diversity-privacy.md
> * https://github.com/web3privacy/docs/blob/main/docs/research/grants.md
> * https://github.com/web3privacy/docs/blob/main/docs/research/privacy-services-db.md

This is something which you should write into web3privacy/docs#4

Please we need to work together on current issues and not create duplicates and making it more complicated 🙏 

I'm closing this issue, and please let's continue in web3privacy/core#37 or sub-issues there.

**Closed by burningtree** 2024-03-02 06:10 UTC
